apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-edit-resources
roleRef:
  kind: Role
  name: edit-resources
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: spark-operator
