kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-resources
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "services", "configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "update", "watch", "patch"]
- apiGroups: ["", "route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
